# Generated by Django 5.2.17 on 2026-10-04 19:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('title_tokens', models.TextField(blank=True, editable=False, verbose_name='タイトルのトークン列')),
                ('body_tokens', models.TextField(blank=True, editable=False, verbose_name='本文のトークン列')),
                ('subtokens', models.TextField(blank=True, editable=False, verbose_name='サブトークン列')),
                ('tokenizer_version', models.CharField(blank=True, editable=False, max_length=50, verbose_name='解析の版')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title_tokens', config='simple', weight='A'), '||', django.contrib.postgres.search.SearchVector('body_tokens', config='simple', weight='B'), django.contrib.postgres.search.SearchConfig('simple')), '||', django.contrib.postgres.search.SearchVector('subtokens', config='simple', weight='C'), django.contrib.postgres.search.SearchConfig('simple')), output_field=django.contrib.postgres.search.SearchVectorField())),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '文書',
                'verbose_name_plural': '文書',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_document_vector_gin')],
            },
        ),
    ]
